name: covid-cg
channels:
  - conda-forge
  - defaults
  - bioconda
dependencies:
  - python=3.8.3
  - numpy=1.18.5
  - scipy=1.6.0
  - pandas=1.0.5
  - xlrd=1.2.0
  - bowtie2=2.4.1
  - pip=20.1.1
  - snakemake=5.20.1
  - samtools=1.10
  - pip:
      - pysam==0.15.4
      # For cloud function development
      - functions-framework==2.0.0
      - google-cloud-storage==1.29.0
  # If you want to run the notebooks:
  - jupyter=1.0.0
  - jupyter_contrib_nbextensions=0.5.1
