# ------------------
#       GLOBAL
# ------------------

# Path to folder with downloaded and processed data
# This path is relative to the workflow folders
data_folder: "../data_genbank"

# Path to folder with genome information (reference.fasta, genes.json, proteins.json)
# This path is relative to the workflow folders
static_data_folder: "../static_data"

# ------------------
#       INGEST
# ------------------

# Number of genomes to load into memory before flushing to disk
chunk_size: 100000

# --------------------
#       ANALYSIS
# --------------------

# SNPs with less than this number of global occurrences will be ignored
snp_count_threshold: 3
# Percentage of sequences within a group (e.g., clade, lineage) that need
# to have a SNV, in order for the SNV to be called as a "consensus" SNV
consensus_fraction: 0.9

metadata_cols:
  database:
    title: "Database"
  host:
    title: "Host"
  isolation_source:
    title: "Isolation source"
  authors:
    title: "Authors"
  publications:
    title: "Publications"

group_cols:
  lineage:
    name: "lineage"
    title: "Lineage"
    description: ""
    link:
      title: "(Lineage Descriptions)"
      href: "https://cov-lineages.org/descriptions.html"

# ---------------
#     SERVER
# ---------------

# Require a login for accessing the website
# Users are provided to the app via. the "LOGINS" environment variable,
# which is structured as "user1:pass1,user2:pass2,..."
login_required: false

dev_hostname: "http://localhost:5000"
prod_hostname: "https://genbank.covidcg.org"
# prod_hostname: "http://localhost:8080"

# ----------------------
#     VISUALIZATION
# ----------------------

show_logos:
  GISAID: false

# Allow downloads of sequence metadata (before aggregation)
allow_metadata_download: true
# Allow downloads of raw genomes
allow_genome_download: true
